### ISSUE TITLE
Awesome work!!!

### ISSUE THREAD

**Issue by SAThomsen** [go-spatial/proj#27]
Just wanted to let you know that this is awesome :) After having to spend an entire day looking into how to convert from WSG84 to UTM32 N Datum 50 natively, I have realized how much this tool is missing in the go eco system. I would love to help if I can, I am however no expert at all in proj4 or geo mappings in general... 

Thank you for putting time into this :)

**Comment by ARolek** [comment]
@SAThomsen nice! Glad it could be of help. @mpgerlek is the mastermind behind this package.
