### ISSUE TITLE
Removing white spaces in ProjStr code

### ISSUE THREAD

**Issue by prl900** [go-spatial/proj#28]
I've come up with an alternative to this TODO:

https://github.com/go-spatial/proj/blob/6ae9eb32ca6a62e7fd60c175d20699e475d1999e/support/ProjString.go#L90

It uses the `regexp` package and the new `collapse` function looks like this:

```
func collapse(s string) string {
        re_leadclose_whtsp := regexp.MustCompile(`^[\s\p{Zs}]+|[\s\p{Zs}]+$`)
    	re_inside_whtsp := regexp.MustCompile(`[\s\p{Zs}]{2,}`)
	re_equal_whtsp := regexp.MustCompile(`\s?[=]\s?`)
    	s = re_leadclose_whtsp.ReplaceAllString(s, "")
    	s = re_inside_whtsp.ReplaceAllString(s, " ")
	s = re_equal_whtsp.ReplaceAllString(s, "=")

        return s
}
```

I can submit a PR if you think it solves the problem.

**Comment by mpgerlek** [comment]
Sure, thanks!

-mpg
