### ISSUE TITLE
API design discussion

### ISSUE THREAD

**Issue by mpgerlek** [go-spatial/proj#3]
_discussion moved here from https://github.com/go-spatial/tegola/issues/267#issuecomment-381252270_

> @ARolek suggests we hard-code a table of SRIDs and their corresponding `proj` strings

This is totally do-able. Taken one step more, and hiding the proj strings from the user, we can provide a set conversions from a geodetic lon/lat of degrees (e.g. 4326) system to a projected system of meters (e.g. 3395). Your suggested function works for this: `proj.Project(from, to uint, point []float64) ([]float64, error)`. We will call this Use Case One.

However, `proj` can do _way_ more stuff than that. It supports 3D coordinate systems, grid files, inverse conversions, complete transforms, and more that I only vaguely can appreciate (like you, I've  just been a passive user of `proj` all these years).

/ping @jj0hns0n 

So the question on the table is, do we really care about that other stuff? The safest answer is usually  "eventually, maybe". That means we don't refactor the core code to support "only Use Case One and never anything else"; instead, we leave the core in a state where it can later be extended as we need to, and add a specialized Use Case One API on top of that core.

And indeed, timing-wise and functionality-wise, the core is in a pretty good place to start doing that right now. It makes sense.

> @ARolek goes on to wonder about "automatically generating" code from `proj` strings

Well, yes-and-no.

You first parse the proj string to understand what sort of conversion (or other beast) is desired, along with the starting datum and ellipse and such. That information tells you how to create the `System` object (called `PJ` in the C code) and which algorithm needs to be run on that system. My code doesn't look at all like the C code anymore, except for the key mathematical fields in the objects.

However, those original algorithms are the parts of `proj.4` that we want to change as little as possible. That code is where the hardcore math is, and in order to be able to carry over bug fixes (or add new projections) we need to keep the code relatively 1:1 with the C.

That said, a lot of the original C code is sort of table-driven in how things get created, and we've kept that model in the new Go code.

**Comment by jj0hns0n** [comment]
+1 for use case one

**Comment by mpgerlek** [comment]
We're going to go with `func Convert(dest EpsgCode, input []float64) ([]float64, error)`, where `EpsgCode` is an enum. The source CRS will implicitly always be `4326`; the operations will always be _conversions_ from lon/lat degrees to x/y meters.

The `System` object that gets created will be cached, so subsequent calls with the same epsg code won't take the setup hit again.

`Convert` is built on top of the `core` package. That package provides the full support for proj strings and such, but we're not going to consider that package "public" at this point.

**Comment by mpgerlek** [comment]
Done!
